version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      WORLD: "/world/world"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - mc:/data
      - ./world:/worlds/world
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "30m"
    volumes:
      - mc:/data:ro
      - ./backups:/backups
    network_mode: "service:mc"

volumes:
  mc: {}